name: GenericEvents
description: Generic events for cross plugin communication
author: StarTux
version: 0.1
api-version: 1.13
website: http://www.winthier.com
main: com.winthier.generic_events.GenericEventsPlugin
depend: []
commands:
  genericevents:
    description: Debug command
    permission: genericevents.genericevents
    usage: |-
      /genericevents itemname - get name of item in hand
      /genericevents permission <player> <perm> - check player permission
permissions: {}
